### ISSUE TITLE
API Key Exposed

### ISSUE THREAD

**Issue by MananGandhi1810** [adityathakurxd/doctordiagnose#1]
By simple inspecting the network tab in any modern web browser, an attacker can access the Gemini API Keys. Please try to secure it, as it may allow anyone to access the APIs, potentially costing you a lot of money (in the case you have access to paid models).

Example:

![image](https://github.com/adityathakurxd/doctordiagnose/assets/67302570/58002ac4-9aed-4923-9858-7fbd5ef5fa51)

**Comment by adityathakurxd** [comment]
Thank you for creating this issue! I was using the ENVied package with the same fear of exposing the API Keys in the browser but it seems like the said package doesn't help here. I have disabled the API Key from the studio. Will look into how best to secure it for Flutter Web and work on a fix.

**Comment by MananGandhi1810** [comment]
Please let me know if I could help you with resolving it in any way. This could help me learn something new.

**Comment by adityathakurxd** [comment]
Sure yes, feel free to suggest a good way to secure the APIs on Web.

**Comment by MananGandhi1810** [comment]
One of the methods I can think of is to use backend and access the API via the backend. The backend can have security features such as rate limiting, CORS and domain checking policies to restrict the API use to your domain ([https://dodiagnose.web.app/](https://dodiagnose.web.app/) in this case). Other option to look upon can be cloud functions on firebase, since I assume you are using firebase to host your project.

**Comment by adityathakurxd** [comment]
Makes sense. Having the API key on the frontend would expose it. It would be better to build a backend and use that.

I do have a railway.app account, I could deploy it on.

**Comment by MananGandhi1810** [comment]
Could I help you with the development of the backend API? That would allow me to gain some experience with actual deployed projects

**Comment by adityathakurxd** [comment]
Yes please, if you would like to take this up, I'd be happy to assign the issue to you.

**Comment by MananGandhi1810** [comment]
Yeah sure, I'll be happy to do that. What tech stack would you recommend? I can work with express.js or flask whatever you say

**Comment by adityathakurxd** [comment]
I'd prefer if you use Express. I haven't worked with Flask and wouldn't be able to review it. 

If you look at the `example` inside Flutter Stripe package you'd see it has a `server` directory with the server side code. Link: https://github.com/flutter-stripe/flutter_stripe/blob/main/example%2Fserver%2Fsrc%2Findex.ts

We can add it in a similar way. Fork the repo, create a server directory at root and add the code to it. Whenever you're ready, create the PR and I can then deploy it to railway.app + merge the PR.

**Comment by MananGandhi1810** [comment]
Sure, I'll us express.js and try to complete this by tomorrow. Will keep you updated with what I'm completing. Thank you for the opportunity 😊
